reviews:
  auto_review: true
  require_review_labels: false
  review_type: extensive        # <-- ensures summaries + macro feedback
  summary: enabled              # <-- YOU DON'T HAVE THIS
  path_includes:
    - "src/**"
    - "app/**"
    - "lib/**"
  path_exclusions:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - ".next/**"
  fail_on:
    - errors
    - blockers

rules:
  max_issue_comments: 30
  severity_threshold: medium

knowledge:
  enable_repo_context: true
